version: "3.2"
services:
  postgres:
    restart: always
    image: postgres:16
    environment:
      POSTGRES_DB: "ems"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
